Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:%s/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxx
  Password: xxx
  IsSSL: true
  From: xxx
  To:
    - xxx
JWT:
  Secret: tom_hello_world_!   # 密钥
  Issuer: gin-tlp-service # 签发者
  Expire: 7200            # 有效时间为 7200 秒
Database:
  DBType: mysql
  UserName: root
  Password: rootroot
  Host: 127.0.0.1:3306
  DBName: GinTlpService
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  SlowThreshold: 3000 # 慢查询超时时间 单位: ms(毫秒)
